### ISSUE TITLE
Freeze version tag until breaking changes are needed

### ISSUE THREAD

**Issue by cjpatton** [ietf-wg-ntp/draft-roughtime#1]
At this point it would be helpful if we stopped bumping the version tag when a purely editorial draft is cut. This allows deployed clients and servers to be forward compatible.

Of course, if breaking changes are needed at some point, then it's appropriate to change the tag as well.

Note that draft-ietf-ntp-roughtime-11 has version `0x8000000b`.

**Comment by dansarie** [comment]
I just made a pull request (#4) that should address this.
