### ISSUE TITLE
Multiple version numbers in requests

### ISSUE THREAD

**Issue by dansarie** [ietf-wg-ntp/draft-roughtime#12]
Currently, sending multiple version numbers in requests is allowed. This complicates server implementations and it is unlikely that clients will send more than one version.

**Comment by dansarie** [comment]
Multiple version numbers is implemented by several servers and clients and seems to be working fine. Maybe it should be kept as is.

**Comment by wbl** [comment]
If it works fine, I think keep it. But I think we needed a change in what is covered in the query to ensure secure negotiation?

**Comment by dansarie** [comment]
We already fixed that by using the hash of the entire query in the Merkle tree, see Section 5.3:
```
For leaf nodes, the byte 0x00 is prepended to the full value of the client's request packet, including the "ROUGHTIM" header, before applying the hash function.
```
This ensures that the root of the tree depends on every bit in all queries.
