### ISSUE TITLE
Grease support

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-wg-ntp/draft-roughtime#2]
[From a mail from](https://mailarchive.ietf.org/arch/msg/ntp/qa0iCrhqeVEtwt28pGH32dSV0sY/) @davidv1992:

> First of all, regarding the ver tag, there is no requirement for
servers to ignore unknown versions in that tag. this means that
technically it is valid behavior right now for a server receiving
unknown versions to reject that packet, even if there is version
overlap. This seems highly undesirable

> Second, the grease section seems to contain no mechanisms for actually
exercising either the ignoring of unknown tags by servers (or clients
for that matter) nor for exercising the version negotiation mechanism.
Given the experience in TLS with this, this is probably a really good
idea to include.

> Finally, the grease section indicates the server must send malformed
packets some amount of the time to clients to exercise the rejection
mechanism, but doesn't specify in which way it may malform the
packets. Thus servers could do this in ways that could potentially
reduce future design space. I would be much more comfortable if we
specified a specific set of things the server is allowed to do to
create malformed packets, so that we at least have control over which
parts of the future design space are excluded.

This was also discussed at [interim](https://datatracker.ietf.org/doc/minutes-interim-2024-ntp-04-202409171500/) yesterday.

**Comment by dansarie** [comment]
I just made a pull request (#4) updating the grease section, which should hopefully be a step towards resolving this. I do not fully understand what the problem described in the first paragraph is. Will ask on the mailing list.

**Comment by dansarie** [comment]
I just made another pull request (#5) clarifying the use of the VER tag in requests, to resolve the problem described in the first paragraph.

**Comment by wbl** [comment]
I think we can close this
