### ISSUE TITLE
Simplification of server response

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-wg-ntp/draft-roughtime#3]
Originally Roughtime just sent over one, fixed cert and at some point switched to having a long lived, and an delegated cert. The current structure of server response is a few layers deep, and I'd propose a flattening out of it. If we represent it as something JSON-like, it should look as of -11 like:

```
{
  VER: uint32,
  PATH: Path,
  INDX: uint32,
  CERT: {
    SIG: ed25519ctx signature,
    DELE: {
      MINT: Timestamp,
      MAXT: Timestamp,
      PUBK: ed25519 public key,
    }
  },
  SIG: edd25519ctx signature,
  SREP: {
    ROOT: Root,
    MIDP: Timestamp,
    RADI: uint32
  }
}
```

What I propose is a slight restructure, flattening out:
```
{
  VER: uint32,
  PATH: Path,
  INDX: uint32,
  CSIG: ed25519ctx signature,
  CERT: {
    MINT: Timestamp,
    MAXT: Timestamp,
    PUBK: ed25519 public key
  },
  TSIG: ed25519ctx signature,
  SREP: {
    ROOT: Root,
    MIDP: Timestamp,
    RADI: uint32
  }
}
```
There's a few reasons for this:
* By having the time and cert signatures with distinct tags, implementers have a clearer delineation of what the tag represents, not based on it's placement in the structure
* Removes a layer of nesting, which is a _tiny_ payload size improvement
* Existing implementations could support this and old without exclusively depending on accurate version reporting - by checking for CSIG (and DELE), validation of CERT/DELE could be handled appropriately.

**Comment by dansarie** [comment]
I'm happy with the way it currently is. If this is implemented, it should be detected through version reporting - anything else just adds complexity and weirdness.

**Comment by wbl** [comment]
I'm going to stick with as is. It's nice to have to signature with the delegation, and I don't think it saves a lot of implementation complexity
