### ISSUE TITLE
Timescales finally

### ISSUE THREAD

**Issue by wbl** [ietf-wg-ntp/draft-roughtime#6]
Do we need to add some more text to clarify what's there?

**Comment by dansarie** [comment]
Which part of the draft are you referring to, use of UTC time in the timestamp (Section 4.1.4) or integration into NTP (Section 6)?

**Comment by wbl** [comment]
Both potentially, but I was mainly thinking about the timestamp and leap seconds. Again.

**Comment by dansarie** [comment]
I updated the text about that in Section 5.2.4 to say that implementations that don't have leap second info SHOULD use a RADI of at least 3. This allows those that know about leap seconds to use smaller RADI most of the time, and adjust accordingly during leap second events. There's probably no other way of doing it without changing the timestamp definition for the nth time. The one thing everyone appears to agree on is the use of UTC.

In any case, we should probably consider being a bit more explicit about our timestamp definition in the text and have a look at the timestamp specification template in RFC 8877.

**Comment by wbl** [comment]
I don't think RFC 8877 covers the issue here, but I think your text is fine. Will reopen if it's a problem
