### ISSUE TITLE
Regression between draft-07 and draft-08

### ISSUE THREAD

**Issue by dansarie** [ietf-wg-ntp/draft-roughtime#9]
In draft-07, we changed the DELE signature context from `RoughTime v1 delegation signature--` to `RoughTime v1 delegation signature`. It then changed back in the following draft. Was this intentional or is it a regression?

**Comment by wbl** [comment]
Sounds like a regression. I plan to go through this week and address a bunch of these issues, forwarding ones that need more input to the list

**Comment by dansarie** [comment]
Fixed by 333da4c5b08871ef99f187ba63a484b7f7c24361.
